### ISSUE TITLE
Failed to Parse urn:cite:hmt:msA.191r δοκέεις

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-utils#125]
urn:cts:greekLit:tlg5026.msA.hmt:15.11@δοκέεις[1]
urn:cts:greekLit:tlg5026.msA.hmt:15.11@δοκέεις[2]
urn:cts:greekLit:tlg5026.msA.hmt:15.12@δοκέεις[1]

It parses in Perseus and morpheus, but is failing in validation

**Comment by neelsmith** [comment]
Your correct analysis means this is a lexmapping issue.  Resolving it there.
