### ISSUE TITLE
Failure to Parse Capitalized Form: urn:cite:hmt:msA.239r Μυρμιδόνων

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-utils#28]
urn:cts:greekLit:tlg5026.msA.hmt:18.8@Μυρμιδόνων[1]
urn:cts:greekLit:tlg5026.msA.hmt:18.8@Μυρμιδόνων[2]
urn:cts:greekLit:tlg5026.msA.hmt:18.9@Μυρμιδόνων[1]
urn:cts:greekLit:tlg5026.msA.hmt:18.10@Μυρμιδόνων[1]
urn:cts:greekLit:tlg5026.msA.hmt:18.10@Μυρμιδόνων[2]
urn:cts:greekLit:tlg0012.tlg001.msA:18.10@Μυρμιδόνων[1]

**Comment by neelsmith** [comment]
Transferring to lexmapping issues tracker.  Closing here.
