### ISSUE TITLE
Parsing error: urn:cite:hmt:msA.240v δηλουμένον

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-utils#29]
urn:cts:greekLit:tlg5026.msA.hmt:18.34@δηλουμένον[1]

surface form: δηλουμένον

should be the present masculine/neuter accusative singular middle-passive participle of δηλόω

**Comment by neelsmith** [comment]
No:  you have the wrong accent.  Wrap in <sic>.  Proper accent is proparoxytone  (acute on antepenult).
