### ISSUE TITLE
Failed to parse: Περι (title of Περι συντάξεως) 

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-utils#30]
περι (lower-case) is a Byzantine equivalent, but the upper-case is not. The scholion is discussing the work Περι συντάξεως, so the capitalization is necessary.

On a related note, does Greek capitalize all the words in a title (Περι Συντάξεως) or just the first word (Περι συντάξεως)?

**Comment by neelsmith** [comment]
need to canonicalize case on all parsing

**Comment by neelsmith** [comment]
Or if this is a Byz ortho variant, just add to byzortho.
