### ISSUE TITLE
urn:cite:hmt:msA.240r, failure to parse: macra

### ISSUE THREAD

**Issue by mwauke** [homermultitext/hmt-utils#37]
Words with macra on them are not parsing. These words are otherwise correctly accented and aspirated.

Examples:  urn:cts:greekLit:tlg0012.tlg001.msA:18.74@ἐξαύδᾱ
urn:cts:greekLit:tlg0012.tlg001.msA:18.72@προσηύδᾱ

**Comment by mwauke** [comment]
Same thing happens with brevia

**Comment by neelsmith** [comment]
tested and passes

**Comment by brclar15** [comment]
This is still an issue. See Charlie's Issue #70 in this repo

**Comment by neelsmith** [comment]
Check sequence of normalizing to/from Unicode NFC before/after conversion to GreekMsString.

**Comment by neelsmith** [comment]
fixed
