### ISSUE TITLE
High stops after persName mark up

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-utils#38]
for some reason the parser fails high stops that appear directly after persName mark up. They pass if you put a white space between the end tag and the high stop.

**Comment by StephanieML** [comment]
and other mark up too

**Comment by neelsmith** [comment]
Desperately need an example

**Comment by StephanieML** [comment]
urn:cts:greekLit:tlg0012.tlg001.msA:15.11@·[1]
    urn:cts:greekLit:tlg0012.tlg001.msA:15.21@·[1]

**Comment by neelsmith** [comment]
fixed
