### ISSUE TITLE
Validation: Lexical Tokens are attributed to the incorrect scholion urn:cite:hmt:msA.248r

### ISSUE THREAD

**Issue by scnevi17** [homermultitext/hmt-utils#80]
When we validated 248r, we found that there were 559 lexical tokens being attributed to the following scholion:
urn:cts:greekLit:tlg5026.msAim.hmt:18.49

According to the validation summary, there are only 577 lexical tokens total, and it appears that there are many more lexical tokens listed on this page than 577.

When we looked into this, we saw that this particular scholion only contains two words, so this could not be correct. One of the words we looked at that was being attributed to this scholion is found in urn:cts:greekLit:tlg5026.msAim.hmt:18.52, which is located on a different folio, 248v.

We have refreshed and pulled on git, to no avail. 

How should we go about this?

**Comment by neelsmith** [comment]
Fixed!
