### ISSUE TITLE
Validation skipping over scholia urn:cite:hmt:msA.250r

### ISSUE THREAD

**Issue by scnevi17** [homermultitext/hmt-utils#83]
None of the words from these intermarginal scholia appear on the lexical tokens page after we have refreshed and validated. They passed in dse, however.
The interlinear scholion urn:cts:greekLit:tlg5026.msAil.hmt:18.35 also was skipped over in validation on this folio.

**Comment by brclar15** [comment]
urn:cite:hmt:msA.251r

Validation shows the main text and the one interior scholion, but neither the one intermarginal nor the one main scholion.

**Comment by neelsmith** [comment]
fixed
