### ISSUE TITLE
Failure to Parse: νείσοντο urn:cite:hmt:msA.250r

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/hmt-utils#84]
urn:cts:greekLit:tlg0012.tlg001.msA:18.566@νείσοντο

The LSJ recognizes νείσομαι (and νείσσομαι)as a legitimate substitute for νίσσομαι, but the word failed to parse both Perseus and Morpheus.

**Comment by neelsmith** [comment]
resolved:  see lexmapping repos.
