### ISSUE TITLE
Failure to parse: urn:cite:hmt:msA.250v ἐγκατεσκευασεν

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/hmt-utils#86]
urn:cts:greekLit:tlg5026.msA.hmt:18.214

ἐγκατεσκευασεν

Already submitted to Byzortho (missing accent).  Still doesn't parse in Perseus or Morpheus.  Should be a valid form from ἐγκατασκευάζω.  (aor. act. ind. 3rd sing.)

**Comment by neelsmith** [comment]
Parses in CLI
