### ISSUE TITLE
Proposed NEW WORD urn:cite:hmt:msA.191r ἀπινύσκων

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/hmt-utils#92]
urn:cts:greekLit:tlg5026.msA.hmt:15.11

Aristophanes lists ἀπινύσκων as being a legitimate alternative of the participle ἀπινύσσων; however, the word fails to parse both the LSJ and Morpheus.

**Comment by neelsmith** [comment]
Is it in LSJ?

**Comment by neelsmith** [comment]
added
