### ISSUE TITLE
Failed to Parse: urn:cite:hmt:msA.191r προπαροξυτονητέον

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/hmt-utils#94]
προπαροξυτονητέον urn:cts:greekLit:tlg5026.msA.hmt:15.15

Verbal adjective form of προπαροξυτονέω which does parse in Perseus. Means to place an accent on the antepenult.

**Comment by neelsmith** [comment]
lexent issue

**Comment by neelsmith** [comment]
resolved:  see lexmapping repos.
