### ISSUE TITLE
Validator is parsing a book number as a word  urn:cite:hmt:msA.245v

### ISSUE THREAD

**Issue by scnevi17** [homermultitext/hmt-utils#97]
urn:cts:greekLit:tlg5026.msA.hmt:18.120

There is a reference to book 23 of the Iliad in this main scholion.  The Ψ is wrapped in a title element but the validator is parsing it as a word.

**Comment by neelsmith** [comment]
Duplicate with isseu 77 https://github.com/homermultitext/hmt-utils/issues/97
